language: node_js
node_js:
  - "5"
  - "4"
branches:
  only:
    - develop
script:
  - brunch b -p
notifications:
  email:
    recipients: prashant@ducic.ac.in
    on_success: change
    on_failure: change
