language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
script:
  - npm run build
notifications:
  email:
    recipients: prashant@ducic.ac.in
    on_success: change
    on_failure: change
