# Site settings
title: Prashant Sinha
email: prashant@ducic.ac.in
description: Personal profile of Prashant Sinha
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://prashnts.github.io"

# Build settings
markdown: kramdown
